### PR TITLE
Message & Claimed "badges"

### PR DESCRIPTION
**Pull request by mhvuze**
I just saw woctezuma's PR, so disregard my inferior Steam store page approach ;)
I added "badges"/styles for games which can still be claimed or are already claimed to give a more consistent look:
alt tag

The message badge also acts as a clickable "button". I also added auto-filling for the PM title. Any idea why auto-filling doesn't work when opened in a new tab btw?

Anyway, there is probably something wrong in terms of sanity but other than that, feel free to merge or improve upon the ideas.

Icons for the badges: http://www.softicons.com/web-icons/bijou-icons-by-visual-idiot

### CODE REVIEW

**Comment by petetnt** [comment]
Hi @mhvuze.

These look really great! I just merged #6 which added the links to store pages. Could you rebase this against the latest master? Would be more than happy to get this in! 👍

**Comment by mhvuze** [comment]
Should be good now 👌

**Comment by woctezuma** [comment]
I have just tested it. Great stuff!

**Comment by petetnt** [comment]
Thanks! I'll review it later today!

**Comment by petetnt** [comment]
Did small changes in 81b0200, otherwise LGTM. Thanks for this great contribution!

**Pull request merged**
